apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pytbak.fullname" . }}-auth
  labels:
    {{- include "pytbak.labels" . | nindent 4 }}
type: Opaque
data:
  DIAG_USERNAME: {{ .Values.auth.username | b64enc | quote }}
  DIAG_PASSWORD: {{ .Values.auth.password | b64enc | quote }}
