name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        context: ./docker/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  docker:
        needs: build
        runs-on: ubuntu-latest
        steps:

        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        # setup Docker buld action
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Login to Github Packages
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GIT_TOKEN }}
      
        - name: Build image and push to Docker Hub and GitHub Container Registry
          uses: docker/build-push-action@v4
          with:
          # relative path to the place where source code with Dockerfile is located
            context: ./docker
            platforms: linux/amd64,linux/arm64
            # Note: tags has to be all lower-case
            tags: |
              lgirardi/pytbak:v-${{ github.run_number }}
          # build on feature branches, push only on main branch
            push: true
            run: docker push lgirardi/pytbak:v-${{ github.run_number }}
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

  security-gate-grype:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: lgirardi/pytbak:v-${{ github.run_number }}
          fail-build: false
          output-format: json

  quality-gate:
    needs: security-gate-grype
    permissions:
      contents: read # for actions/checkout to fetch code
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          directory: .
          output_format: sarif
          soft_fail: true
          quiet: true

  modifygit:
    needs: quality-gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: modify the image
        run: |
          git config user.email l@k8s.it
          git config user.name l
          cd kubernetes/
          cat 04-dpl-pytbak.yaml
          pwd
          sed -i "s+lgirardi/pytbak.*+lgirardi/pytbak:v-$RUN_NUMBER+g" 04-dpl-pytbak.yaml
          cat 04-dpl-pytbak.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
