name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  security-events: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: Harden Runner
          uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
          with:
            egress-policy: audit

        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        # setup Docker buld action
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Login to Github Packages
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GIT_TOKEN }}
      
        - name: Build image and push to Docker Hub and GitHub Container Registry
          uses: docker/build-push-action@v6
          with:
            context: ./docker
            cache-from: type=gha
            cache-to: type=gha,mode=max
            platforms: linux/amd64,linux/arm64
            tags: |
              lgirardi/pytbak:v-${{ github.run_number }}
            push: true
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

  security-gate-trivy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Scan image
        uses: aquasecurity/trivy-action@0.30.0
        id: scan
        with:
          image-ref: lgirardi/pytbak:v-${{ github.run_number }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
             
  docker-sbom:
    needs: security-gate-trivy
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Sbom image
        uses: anchore/sbom-action@v0
        continue-on-error: true
        id: sbom
        with:
          image: lgirardi/pytbak:v-${{ github.run_number }}
          output-file: "${{ github.event.repository.name }}-sbom.spdx.json"

  quality-gate:
    needs: docker-sbom
    permissions:
      contents: read # for actions/checkout to fetch code
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      # Checks-out your repository under $GITHUB_WORKSPACE, so follow-up steps can access it
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        id: checkov
        with:
          # This will add both a CLI output to the console and create a results.sarif file
          framework: kubernetes
          directory: ./kubernetes/
          output_format: sarif
          soft_fail: true
          quiet: true

  modifygit:
    needs: quality-gate
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: modify the image
        run: |
          git config user.email l@k8s.it
          git config user.name l
          cd kubernetes/
          cat 04-dpl-pytbak.yaml
          pwd
          sed -i "s+lgirardi/pytbak.*+lgirardi/pytbak:v-$RUN_NUMBER+g" 04-dpl-pytbak.yaml
          cat 04-dpl-pytbak.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}

  k8s-check:
    needs: modifygit
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Testing on a k8s Kind Cluster
        uses: helm/kind-action@v1.12.0
      - run: |
          kubectl cluster-info
          kubectl get nodes
      - name : Preparing cluster for kube-check
        run: |
          kubectl run kube-check --image=lgirardi/pytbak:v-${{ github.run_number }} --port=5000
          sleep 20
          kubectl get po
          kubectl port-forward kube-check 5000:5000 &>/dev/null &
          sleep 5
          kubectl port-forward kube-check 5000:5000 &>/dev/null &
      - run: |
          curl -I http://localhost:5000/api/
